workflows:
  release-workflow:
    name: Flutter Release Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      groups:
        - keystore_credentials
    scripts:
      - name: Decode and save Keystore file
        script: |
          echo $CM_KEYSTORE | base64 --decode > /tmp/keystore.jks

      - name: Get Flutter dependencies
        script: |
          flutter pub get

      - name: Build Signed APK
        script: |
          flutter build apk --release \
            --dart-define=KEYSTORE_PATH=/tmp/keystore.jks \
            --dart-define=KEYSTORE_ALIAS=$CM_KEY_ALIAS \
            --dart-define=KEYSTORE_PASSWORD=$CM_KEYSTORE_PASSWORD \
            --dart-define=KEY_PASSWORD=$CM_KEY_PASSWORD

      - name: Build Signed AAB
        script: |
          flutter build appbundle --release \
            --dart-define=KEYSTORE_PATH=/tmp/keystore.jks \
            --dart-define=KEYSTORE_ALIAS=$CM_KEY_ALIAS \
            --dart-define=KEYSTORE_PASSWORD=$CM_KEYSTORE_PASSWORD \
            --dart-define=KEY_PASSWORD=$CM_KEY_PASSWORD

    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab

    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: production
