workflows:
  android-release:
    name: Android Release Build
    environment:
      flutter: stable
      groups:
        - google_credentials
      vars:
        PACKAGE_NAME: "com.example.members_lists"  # Replace with your actual package name
        KEYSTORE_PATH: $CM_BUILD_DIR/android/app/upload-keystore.jks
        KEYSTORE_PASSWORD: $CM_KEYSTORE_PASSWORD
        KEY_ALIAS: $CM_KEY_ALIAS
        KEY_PASSWORD: $CM_KEY_PASSWORD
    scripts:
      - name: Set up keystore
        script: |
          echo $CM_KEYSTORE | base64 --decode > $KEYSTORE_PATH
      - name: Get Flutter dependencies
        script: |
          flutter packages get
      - name: Build APK
        script: |
          flutter build apk --release
      - name: Build App Bundle
        script: |
          flutter build appbundle --release
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
