workflows:
  release-workflow:
    name: Flutter Release Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      groups:
        - keystore_credentials
    scripts:
      - name: Decode and save Keystore file
        script: |
          echo $CM_KEYSTORE | base64 --decode > android/app/keystore.jks

      - name: Set up Key Properties
        script: |
          cat > android/key.properties <<EOF
          storePassword=$CM_KEYSTORE_PASSWORD
          keyPassword=$CM_KEY_PASSWORD
          keyAlias=$CM_KEY_ALIAS
          storeFile=keystore.jks
          EOF

      - name: Get Flutter dependencies
        script: |
          flutter pub get

      - name: Build Signed AAB
        script: |
          flutter build appbundle --release

    artifacts:
      - build/**/outputs/**/*.aab

    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: production
