workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      groups:
        - google_credentials # Reference to the Play Store API JSON key
      vars:
        PACKAGE_NAME: "com.example.members_lists" # Replace with your actual package name
    scripts:
      - name: Install dependencies
        script: flutter pub get

      - name: Build AAB
        script: flutter build appbundle

    artifacts:
      - build/app/outputs/bundle/release/app-release.aab

    publishing:
      google_play:
        credentials: $GOOGLE_CREDENTIALS
        track: internal
